# Generated by Django 5.2.6 on 2025-09-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('value', models.SmallIntegerField(choices=[(-1, 'dislike'), (1, 'like')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('post', 'username'), name='unique_reaction_per_user_post')],
            },
        ),
    ]
